export const MUSIC_GET_TRENDING = "MUSIC_GET_TRENDING";
export const MUSIC_GET_TRENDING_FAILED = "MUSIC_GET_TRENDING_FAILED";
export const MUSIC_GET_ROMANTIC_VIDEOS = "MUSIC_GET_ROMANTIC_VIDEOS";
export const MUSIC_GET_PLAYLIST_FAILED = "MUSIC_GET_PLAYLIST_FAILED";

export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
